name: svo_filters-3.10
channels:
  - defaults
  - http://ssb.stsci.edu/astroconda
dependencies:
  - astropy>=5.3.1
  - bokeh>=3.2.1
  - matplotlib
  - numpy>=1.25.1
  - numpydoc=1.1.0
  - pytest>=7.4.0
  - python>=3.10
  - pip:
    - PyYAML>=5.4
    - sphinx_astropy==1.3
    - astroquery